server:
  port: 8080


spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=library_management
    username: test
    password: test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@test.com
    password: test
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    path: logs/application.log


app:
  max-books-allowed: 5
  late-fee-threshold: 14
